remote_theme: "mmistakes/minimal-mistakes@4.20.1"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

defaults:
  # _docs
  - scope:
      path: ""
    values:
      sidebar:
        nav: "docs"
