remote_theme: "mmistakes/minimal-mistakes@4.20.1"

plugins:
  - jekyll-include-cache
  - jekyll-sitemap

share: true

defaults:
  - scope:
      path: ""
      type: pages
    values:
      sidebar:
        nav: "docs"